# Basic information about this project
[content]
name = "Ws3ModTemlateProject"
description = "Add awesome haptic feedback to varius Geralt actions"
version = "1.0.0"
authors = [ "yourName" ]
game_version = "4.04"
scripts_root = "scripts"

# Any dependencies that this project might need
[dependencies]
content0 = true

# For details check the manual
# https://spontancombust.github.io/witcherscript-ide/user-manual/project-system/#manifest-format
